# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65c796e87c55ba86de6ae4cb21c94fb28952c890deb8f45b7f37e948fa98b7f36def695eb3e625518a505b8c7d640726efdd698d50956c3c2eac7b9ef3e616fb

test:
  secret_key_base: 9de55f6e104bb321483a3cf483b29d3e092ac45bea0760113a5424ac69abab0c7725fb350f926d0fad6723fa383a70f0de27d41ba75df0591979e7fbe1090261

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
